version: "1.0"
info:
  model: int-scaffold
packages:
- name: DacherPoCProject
  gitServerName: DacherCustomerRepo
  gitUrl: https://github.com/Bharath-Meka-0058MR744
  gitUsername: Bharath-Meka-0058MR744
  gitBranch: main
- name: smtprepo
  version: "1.1"
  gitServerName: DacherCustomerRepo
  gitUrl: https://github.com/Bharath-Meka-0058MR744
  gitUsername: Bharath-Meka-0058MR744
  gitBranch: main
- name: webServicesRepo
  version: "1.2"
  gitServerName: DacherCustomerRepo
  gitUrl: https://github.com/Bharath-Meka-0058MR744
  gitUsername: Bharath-Meka-0058MR744
  gitBranch: main
- name: sftprepo
  version: "1.2"
  gitServerName: DacherCustomerRepo
  gitUrl: https://github.com/Bharath-Meka-0058MR744
  gitUsername: Bharath-Meka-0058MR744
  gitBranch: main
services:
- serviceName: project.dacherpoc.integrations:sftpCheck
  packages:
  - name: DacherPoCProject
    version: "1.0"
  - name: sftprepo
    version: "1.2"
  - name: webServicesRepo
    version: "1.2"
  - name: smtprepo
    version: "1.1"
- serviceName: com.dachser:readFileList
  packages:
  - name: sftprepo
    version: "1.2"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.1
- serviceName: pub.flow:setCustomContextID
  packages:
  - name: WmPublic
    version: 11.1.0.0.1
- serviceName: pub.client.sftp:login
  packages:
  - name: WmPublic
    version: 11.1.0.0.1
- serviceName: pub.client.sftp:ls
  packages:
  - name: WmPublic
    version: 11.1.0.0.1
- serviceName: pub.list:sizeOfList
  packages:
  - name: WmPublic
    version: 11.1.0.0.1
- serviceName: pub.client.sftp:logout
  packages:
  - name: WmPublic
    version: 11.1.0.0.1
- serviceName: com.dachser:getFile
  packages:
  - name: sftprepo
    version: "1.2"
- serviceName: pub.client.sftp:get
  packages:
  - name: WmPublic
    version: 11.1.0.0.1
- serviceName: pub.io:streamToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.1
configurationVariables:
  jdbc.jdbcTestPool.waitingThread: "0"
  jdbc.jdbcTestPool.minConns: "0"
  jdbc.jdbcTestPool.expireTime: "60000"
  jdbc.jdbcTestPool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/jdbcTestPool.log;ddtdbg.ProtocolTraceShowTime=true
  jdbc.jdbcTestPool.maxConns: "10"
  jdbc.jdbcTestPool.userid: root
  jdbc.jdbcTestPool.driverAlias: MySQL Database Java Connector Driver
  jdbc.jdbcTestPool.spyenabled: "false"
  jdbc.jdbcTestPool.snoopenabled: "false"
  jdbc.jdbcTestPool.password: "{AES}er+I3U8nDVm8F4DBRST1+A=="
  jdbc.jdbcTestPool.spyparms: SpyAttributes=(log=(file)logs/spy/jdbcTestPool.log;logTName=yes;timestamp=yes)
  jdbc.jdbcTestPool.dbURL: jdbc:mysql://mysql.test.local:3306/webm
  jdbc.jdbcTestPool.poolThreshold: "0"
  jdbc.jdbcTestPool.useSSL: "false"
